FROM centos AS builder

ENV PKG_CONFIG_PATH $PKG_CONFIG_PATH:/usr/local/lib/pkgconfig

# For FFMPEG4.1
ADD nasm-2.14.tar.bz2 /tmp
ADD yasm-1.2.0.tar.bz2 /tmp
ADD fdk-aac-0.1.3.tar.bz2 /tmp
ADD lame-3.99.5.tar.bz2 /tmp
ADD speex-1.2rc1.tar.bz2 /tmp
ADD x264-snapshot-20181116-2245.tar.bz2 /tmp
ADD ffmpeg-4.1.tar.bz2 /tmp
ADD openssl-1.1.0e.tar.bz2 /tmp
ADD srs.tar.bz2  /usr/local
RUN yum install -y gcc gcc-c++ make patch sudo && \
    yum install -y unzip perl zlib && \
    yum install -y automake libtool zlib-devel && \
    cd /tmp/nasm-2.14 && ./configure  && make -j4 && make install && \
    cd /tmp/yasm-1.2.0 && ./configure  && make -j4 && make install && \
    cd /tmp/fdk-aac-0.1.3 && bash autogen.sh && ./configure  --enable-static && make && make install && \
    cd /tmp/lame-3.99.5 && ./configure  --enable-static && make -j4 && make install && \
    cd /tmp/speex-1.2rc1 && ./configure  --enable-static && make -j4 && make install && \
    cd /tmp/x264-snapshot-20181116-2245 && ./configure  --disable-cli --enable-static && make -j4 && make install && \
    yum install -y bzip2 bzip2-devel && \
    #RUN rm -f /usr/local/lib/*.so*
    cd /tmp/ffmpeg-4.1 && ./configure  --enable-gpl --enable-nonfree \
	--enable-static --disable-shared --enable-postproc --enable-bzlib --enable-zlib \
	--enable-parsers --enable-libx264 --enable-libmp3lame --enable-libfdk-aac \
	--enable-libspeex --enable-pthreads --extra-libs=-lpthread --enable-encoders \
	--enable-decoders --enable-avfilter --enable-muxers --enable-demuxers && make -j4 && make install && \

    ln -sf /usr/local/lib/libfdk-aac.so.0 /lib64/ && \
	ln -sf /usr/local/lib/libmp3lame.so.0 /lib64/ && \
	ln -sf /usr/local/lib/libspeex.so.1 /lib64/ && \
	# For GIT
    yum install -y git && \
    git config --global alias.co checkout && \
	git config --global alias.br branch && \
	git config --global alias.ci commit && \
	git config --global alias.st status && \
	git config --global alias.sm submodule && \
    # Openssl
    cd /tmp/openssl-1.1.0e && ./config -no-shared no-threads && make && make install_sw && \
    # For ifconfig
    yum install -y net-tools && \
    cd /usr/local/srs/trunk && bash ./configure  --with-ffmpeg && make -j4 && make install &&\
    #clean up
    rm -rf /tmp/* &&\
    yum autoremove -y gcc gcc-c++ kernel-headers git go wget automake autoconf make patch unzip && \
    rm -rf /usr/local/srs/trunk/doc/* &&\
    cd /usr/local/srs/trunk && \
    find . -name '*.c' -type f -exec rm -rf {} \; && \
    find . -name '*.o' -type f -exec rm -rf {} \; && \
    find . -name '*.h' -type f -exec rm -rf {} \; && \
    find . -name '*.cpp' -type f -exec rm -rf {} \; && \
    find . -name '*.hpp' -type f -exec rm -rf {} \; && \
    find . -name '*.zip' -type f -exec rm -rf {} \; && \
    find . -type d -empty -delete && \
    yum clean all
FROM centos
COPY --from=builder / /
COPY ./srs.conf /usr/local/srs/trunk/conf/srs.conf
RUN touch /usr/local/srs/trunk/objs/srs.log
EXPOSE 1935 1985 8080
WORKDIR /usr/local/srs/trunk
#CMD ["./objs/srs", "-c", "conf/srs.conf"]
CMD ["/bin/sh","-c","objs/srs -c conf/srs.conf && tail -f objs/srs.log"]
